version: 2
jobs:
  build:
    branches:
      ignore: gh-pages
    docker:
      - image: circleci/node:11.4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "lectures/package.json" }}
            - v1-dependencies-

      - run: |
          cd lectures
          npm install
          cd ..

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "lectures/package.json" }}

      - run:
          name: generate main html page
          command: |
            mkdir _site
            cp .assets/template.html _site/index.html
            lectures/node_modules/marked/bin/marked -i README.md >> _site/index.html
            cat .assets/template_end.html >> _site/index.html
            cp *.png _site/
            cp *.jpg _site/

      - run:
          name: generate static reveal.js slides
          command: |
            cd lectures
            npm run generate
            cp -r _static/ ../_site/slides
            cd ..

      - add_ssh_keys:
          fingerprints:
            - "86:ba:3d:bf:47:f3:b4:24:8f:cc:bb:34:53:10:3f:e1"
      - run:
          name: deploy _site directory to gh-pages
          command: |
            touch _site/.nojekyll
            git config user.email "ci-build@cs.cmu.edu"
            git config user.name "ci-build"
            node lectures/node_modules/gh-pages/bin/gh-pages.js -t --dist _site -m 'update static slides [ci skip]'
